//all notification receptionist
export const GET_ALL_NOTIFICATION_RECEPTIONIST = "GET_ALL_NOTIFICATION_RECEPTIONIST";
export const GET_ALL_NOTIFICATION_SUCCESS_RECEPTIONIST = "GET_ALL_NOTIFICATION_SUCCESS_RECEPTIONIST";
export const GET_ALL_NOTIFICATION_ERROR_RECEPTIONIST = "GET_ALL_NOTIFICATION_ERROR_RECEPTIONIST";

//all feedback
export const GET_ALL_FEEDBACK_REQUEST = "GET_ALL_FEEDBACK_REQUEST";
export const GET_ALL_FEEDBACK_SUCCESS = "GET_ALL_FEEDBACK_SUCCESS";
export const GET_ALL_FEEDBACK_ERROR = "GET_ALL_FEEDBACK_ERROR";