//all notification receptionist
export const GET_ALL_NOTIFICATION_RECEPTIONIST = "GET_ALL_NOTIFICATION_RECEPTIONIST";
export const GET_ALL_NOTIFICATION_SUCCESS_RECEPTIONIST = "GET_ALL_NOTIFICATION_SUCCESS_RECEPTIONIST";
export const GET_ALL_NOTIFICATION_ERROR_RECEPTIONIST = "GET_ALL_NOTIFICATION_ERROR_RECEPTIONIST";

//all feedback
export const GET_ALL_FEEDBACK_REQUEST = "GET_ALL_FEEDBACK_REQUEST";
export const GET_ALL_FEEDBACK_SUCCESS = "GET_ALL_FEEDBACK_SUCCESS";
export const GET_ALL_FEEDBACK_ERROR = "GET_ALL_FEEDBACK_ERROR";

//mask as read
export const MASK_AS_READ_REQUEST = "MASK_AS_READ_REQUEST";
export const MASK_AS_READ_SUCCESS = "MASK_AS_READ_SUCCESS";
export const MASK_AS_READ_ERROR = "MASK_AS_READ_ERROR";

//get all table
export const GET_ALL_TABLE_RECEPTIONIST_REQUEST = "GET_ALL_TABLE_RECEPTIONIST_REQUEST";
export const GET_ALL_TABLE_RECEPTIONIST_SUCCESS = "GET_ALL_TABLE_RECEPTIONIST_SUCCESS";
export const GET_ALL_TABLE_RECEPTIONIST_ERROR = "GET_ALL_TABLE_RECEPTIONIST_ERROR";

//add table
export const ADD_TABLE_RECEPTIONIST_REQUEST = "ADD_TABLE_RECEPTIONIST_REQUEST";
export const ADD_TABLE_RECEPTIONIST_SUCCESS = "ADD_TABLE_RECEPTIONIST_SUCCESS";
export const ADD_TABLE_RECEPTIONIST_ERROR = "ADD_TABLE_RECEPTIONIST_ERROR";

//delete table
export const DELETE_TABLE_RECEPTIONIST_REQUEST = "DELETE_TABLE_RECEPTIONIST_REQUEST";
export const DELETE_TABLE_RECEPTIONIST_SUCCESS = "DELETE_TABLE_RECEPTIONIST_SUCCESS";
export const DELETE_TABLE_RECEPTIONIST_ERROR = "DELETE_TABLE_RECEPTIONIST_ERROR";

//generate table
export const GENERATE_TABLE_RECEPTIONIST_REQUEST = "GENERATE_TABLE_RECEPTIONIST_REQUEST";
export const GENERATE_TABLE_RECEPTIONIST_SUCCESS = "GENERATE_TABLE_RECEPTIONIST_SUCCESS";
export const GENERATE_TABLE_RECEPTIONIST_ERROR = "GENERATE_TABLE_RECEPTIONIST_ERROR";

//edit table
export const EDIT_TABLE_RECEPTIONIST_REQUEST = "EDIT_TABLE_RECEPTIONIST_REQUEST";
export const EDIT_TABLE_RECEPTIONIST_SUCCESS = "EDIT_TABLE_RECEPTIONIST_SUCCESS";
export const EDIT_TABLE_RECEPTIONIST_ERROR = "EDIT_TABLE_RECEPTIONIST_ERROR";