//all notification kitchen
export const GET_ALL_NOTIFICATION_KITCHEN = "GET_ALL_NOTIFICATION_KITCHEN";
export const GET_ALL_NOTIFICATION_SUCCESS_KITCHEN = "GET_ALL_NOTIFICATION_SUCCESS_KITCHEN";
export const GET_ALL_NOTIFICATION_ERROR_KITCHEN = "GET_ALL_NOTIFICATION_ERROR_KITCHEN";

//mask as read
export const MASK_AS_READ_KITCHEN_REQUEST = "MASK_AS_READ_KITCHEN_REQUEST";
export const MASK_AS_READ_KITCHEN_SUCCESS = "MASK_AS_READ_KITCHEN_SUCCESS";
export const MASK_AS_READ_KITCHEN_ERROR = "MASK_AS_READ_KITCHEN_ERROR";

//view all dish in confirm
export const GET_ALL_DISH_IN_CONFIRM_REQUEST = "GET_ALL_DISH_IN_CONFIRM_REQUEST";
export const GET_ALL_DISH_IN_CONFIRM_SUCCESS = "GET_ALL_DISH_IN_CONFIRM_SUCCESS";
export const GET_ALL_DISH_IN_CONFIRM_ERROR = "GET_ALL_DISH_IN_CONFIRM_ERROR";

//view all dish in completed
export const GET_ALL_DISH_IN_COMPLETED_REQUEST = "GET_ALL_DISH_IN_COMPLETED_REQUEST";
export const GET_ALL_DISH_IN_COMPLETED_SUCCESS = "GET_ALL_DISH_IN_COMPLETED_SUCCESS";
export const GET_ALL_DISH_IN_COMPLETED_ERROR = "GET_ALL_DISH_IN_COMPLETED_ERROR";

//update status of dish
export const UPDATE_STATUS_OF_DISH_REQUEST = "UPDATE_STATUS_OF_DISH_REQUEST";
export const UPDATE_STATUS_OF_DISH_SUCCESS = "UPDATE_STATUS_OF_DISH_SUCCESS";
export const UPDATE_STATUS_OF_DISH_ERROR = "UPDATE_STATUS_OF_DISH_ERROR";

//get all list of item
export const GET_ALL_LIST_ITEM_REQUEST = "GET_ALL_LIST_ITEM_REQUEST";
export const GET_ALL_LIST_ITEM_SUCCESS = "GET_ALL_LIST_ITEM_SUCCESS";
export const GET_ALL_LIST_ITEM_ERROR = "GET_ALL_LIST_ITEM_ERROR";

//update item can serve
export const UPDATE_ITEM_CAN_SERVE_REQUEST = "UPDATE_ITEM_CAN_SERVE_REQUEST";
export const UPDATE_ITEM_CAN_SERVE_SUCCESS = "UPDATE_ITEM_CAN_SERVE_SUCCESS";
export const UPDATE_ITEM_CAN_SERVE_ERROR = "UPDATE_ITEM_CAN_SERVE_ERROR";