//total new notifications
export const TOTAL_OF_NOTIFICATIONS_REQUEST = "TOTAL_OF_NOTIFICATIONS_REQUEST";
export const TOTAL_NOTIFICATIONS_SUCCESS = "TOTAL_NOTIFICATIONS_SUCCESS";
export const TOTAL_NOTIFICATIONS_ERROR = "TOTAL_NOTIFICATIONS_ERROR";

//all notification
export const GET_ALL_NOTIFICATION = "GET_ALL_NOTIFICATION";
export const GET_ALL_NOTIFICATION_SUCCESS = "GET_ALL_NOTIFICATION_SUCCESS";
export const GET_ALL_NOTIFICATION_ERROR = "GET_ALL_NOTIFICATION_ERROR";

//all table

export const GET_ALL_TABLE_REQUEST = "GET_ALL_TABLE_REQUEST";
export const GET_ALL_TABLE_SUCCESS = "GET_ALL_TABLE_SUCCESS";
export const GET_ALL_TABLE_ERROR = "GET_ALL_TABLE_ERROR";

//get table by id
export const GET_TABLE_REQUEST = "GET_TABLE_REQUEST";
export const GET_TABLE_SUCCESS = "GET_TABLE_SUCCESS";
export const GET_TABLE_ERROR = "GET_TABLE_ERROR";

//Update table by id
export const POST_UPDATE_TABLE_REQUEST = "POST_UPDATE_TABLE_REQUEST";
export const POST_UPDATE_TABLE_SUCCESS = "POST_UPDATE_TABLE_SUCCESS";
export const POST_UPDATE_TABLE_ERROR = "POST_UPDATE_TABLE_ERROR ";
// Log out
export const GET_LOG_OUT_REQUEST = "GET_LOG_OUT_REQUEST";
export const GET_LOG_OUT_SUCCESS = "GET_LOG_OUT_SUCCESS";
export const GET_LOG_OUT_ERROR = "GET_LOG_OUT_ERROR ";