//total new notifications
export const TOTAL_OF_NOTIFICATIONS_REQUEST = "TOTAL_OF_NOTIFICATIONS_REQUEST";
export const TOTAL_NOTIFICATIONS_SUCCESS = "TOTAL_NOTIFICATIONS_SUCCESS";
export const TOTAL_NOTIFICATIONS_ERROR = "TOTAL_NOTIFICATIONS_ERROR";

//all notification
export const GET_ALL_NOTIFICATION = "GET_ALL_NOTIFICATION";
export const GET_ALL_NOTIFICATION_SUCCESS = "GET_ALL_NOTIFICATION_SUCCESS";
export const GET_ALL_NOTIFICATION_ERROR = "GET_ALL_NOTIFICATION_ERROR";

//all table

export const GET_ALL_TABLE_REQUEST = "GET_ALL_TABLE_REQUEST";
export const GET_ALL_TABLE_SUCCESS = "GET_ALL_TABLE_SUCCESS";
export const GET_ALL_TABLE_ERROR = "GET_ALL_TABLE_ERROR";

//get table by id
export const GET_TABLE_REQUEST = "GET_TABLE_REQUEST";
export const GET_TABLE_SUCCESS = "GET_TABLE_SUCCESS";
export const GET_TABLE_ERROR = "GET_TABLE_ERROR";

//Update table by id
export const POST_UPDATE_TABLE_REQUEST = "POST_UPDATE_TABLE_REQUEST";
export const POST_UPDATE_TABLE_SUCCESS = "POST_UPDATE_TABLE_SUCCESS";
export const POST_UPDATE_TABLE_ERROR = "POST_UPDATE_TABLE_ERROR ";
// Log out
export const GET_LOG_OUT_REQUEST = "GET_LOG_OUT_REQUEST";
export const GET_LOG_OUT_SUCCESS = "GET_LOG_OUT_SUCCESS";
export const GET_LOG_OUT_ERROR = "GET_LOG_OUT_ERROR ";

// Check List
export const GET_CHECK_LIST_PREPARE_REQUEST = "GET_CHECK_LIST_PREPARE_REQUEST";
export const GET_CHECK_LIST_PREPARE_SUCCESS = "GET_CHECK_LIST_PREPARE_SUCCESS";
export const GET_CHECK_LIST_PREPARE_ERROR = "GET_CHECK_LIST_PREPARE_ERROR ";

// Check List
export const GET_CHECK_LIST_COMPLETE_REQUEST = "GET_CHECK_LIST_COMPLETE_REQUEST";
export const GET_CHECK_LIST_COMPLETE_SUCCESS = "GET_CHECK_LIST_COMPLETE_SUCCESS";
export const GET_CHECK_LIST_COMPLETE_ERROR = "GET_CHECK_LIST_COMPLETE_ERROR ";

// Check close table
export const GET_CLOSE_TABLE_REQUEST = "GET_CLOSE_TABLE_REQUEST";
export const GET_CLOSE_TABLE_SUCCESS = "GET_CLOSE_TABLE_SUCCESS";
export const GET_CLOSE_TABLE_ERROR = "GET_CLOSE_TABLE_ERROR ";


// Delete item
export const POST_DELETE_ITEM_REQUEST = "POST_DELETE_ITEM_REQUEST";
export const POST_DELETE_ITEM_SUCCESS = "POST_DELETE_ITEM_SUCCESS";
export const POST_DELETE_ITEM_ERROR = "POST_DELETE_ITEM_ERROR ";

// search item
export const GET_SEARCH_ITEM_REQUEST = "GET_SEARCH_ITEM_REQUEST";
export const GET_SEARCH_ITEM_SUCCESS = "GET_SEARCH_ITEM_SUCCESS";
export const GET_SEARCH_ITEM_ERROR = "GET_SEARCH_ITEM_ERROR ";

// detail item
export const GET_DETAIL_ITEM_REQUEST = "GET_DETAIL_ITEM_REQUEST";
export const GET_DETAIL_ITEM_SUCCESS = "GET_DETAIL_ITEM_SUCCESS";
export const GET_DETAIL_ITEM_ERROR = "GET_DETAIL_ITEM_ERROR ";

// Insert item
export const POST_INSERT_ITEM_REQUEST = "POST_INSERT_ITEM_REQUEST";
export const POST_INSERT_ITEM_SUCCESS = "POST_INSERT_ITEM_SUCCESS";
export const POST_INSERT_ITEM_ERROR = "POST_INSERT_ITEM_ERROR ";