//total new notifications
export const TOTAL_OF_NOTIFICATIONS_REQUEST = "TOTAL_OF_NOTIFICATIONS_REQUEST";
export const TOTAL_NOTIFICATIONS_SUCCESS = "TOTAL_NOTIFICATIONS_SUCCESS";
export const TOTAL_NOTIFICATIONS_ERROR = "TOTAL_NOTIFICATIONS_ERROR";

//all notification
export const GET_ALL_NOTIFICATION = "GET_ALL_NOTIFICATION";
export const GET_ALL_NOTIFICATION_SUCCESS = "GET_ALL_NOTIFICATION_SUCCESS";
export const GET_ALL_NOTIFICATION_ERROR = "GET_ALL_NOTIFICATION_ERROR";
