
export const POST_NUMBER_CUSTOMER= "POST_NUMBER_CUSTOMER";
export const POST_NUMBER_CUSTOMER_SUCCESS = "POST_NUMBER_CUSTOMER_SUCCESS";
export const POST_NUMBER_CUSTOMER_ERROR = "POST_NUMBER_CUSTOMER_ERROR";

export const POST_CLOSE_TABLE_REQUEST= "POST_CLOSE_TABLE_REQUEST";
export const POST_CLOSE_TABLE_SUCCESS = "POST_CLOSE_TABLE_SUCCESS";
export const POST_CLOSE_TABLE_ERROR = "POST_CLOSE_TABLE_ERROR";

export const POST_MARK_AS_READ_REQUEST= "POST_MARK_AS_READ_REQUEST";
export const POST_MARK_AS_READ_SUCCESS = "POST_MARK_AS_READ_SUCCESS";
export const POST_MARK_AS_READ_ERROR = "POST_MARK_AS_READ_ERROR";

// view queue order
export const GET_QUEUE_ORDER_REQUEST= "GET_QUEUE_ORDER_REQUEST";
export const GET_QUEUE_ORDER_SUCCESS = "GET_QUEUE_ORDER_SUCCESS";
export const GET_QUEUE_ORDER_ERROR = "GET_QUEUE_ORDER_ERROR";


// cancel queue order
export const POST_CANCEL_QUEUE_ORDER_REQUEST= "POST_CANCEL_QUEUE_ORDER_REQUEST";
export const POST_CANCEL_QUEUE_ORDER_SUCCESS = "POST_CANCEL_QUEUE_ORDER_SUCCESS";
export const POST_CANCEL_QUEUE_ORDER_ERROR = "POST_CANCEL_QUEUE_ORDER_ERROR";

// confirm queue order
export const POST_CONFIRM_QUEUE_ORDER_REQUEST= "POST_CONFIRM_QUEUE_ORDER_REQUEST";
export const POST_CONFIRM_QUEUE_ORDER_SUCCESS = "POST_CONFIRM_QUEUE_ORDER_SUCCESS";
export const POST_CONFIRM_QUEUE_ORDER_ERROR = "POST_CONFIRM_QUEUE_ORDER_ERROR";

// View detail confirmed order
export const GET_CONFIRMED_ORDER_REQUEST= "GET_CONFIRMED_ORDER_REQUEST";
export const GET_CONFIRMED_ORDER_SUCCESS = "GET_CONFIRMED_ORDER_SUCCESS";
export const GET_CONFIRMED_ORDER_ERROR = "GET_CONFIRMED_ORDER_ERROR";

// delete item in confirm order
export const POST_DELETE_ITEM_REQUEST= "POST_DELETE_ITEM_REQUEST";
export const POST_DELETE_ITEM_SUCCESS = "POST_DELETE_ITEM_SUCCESS";
export const POST_DELETE_ITEM_ERROR = "POST_DELETE_ITEM_ERROR";

// delete item in queue order
export const POST_DELETE_QUEUE_ITEM_REQUEST= "POST_DELETE_QUEUE_ITEM_REQUEST";
export const POST_DELETE_QUEUE_ITEM_SUCCESS = "POST_DELETE_QUEUE_ITEM_SUCCESS";
export const POST_DELETE_QUEUE_ITEM_ERROR = "POST_DELETE_QUEUE_ITEM_ERROR";


// post change table
export const POST_CHANGE_TABLE_REQUEST= "POST_CHANGE_TABLE_REQUEST";
export const POST_CHANGE_TABLE_SUCCESS = "POST_CHANGE_TABLE_SUCCESS";
export const POST_CHANGE_TABLE_ERROR = "POST_CHANGE_TABLE_ERROR";

// post update status drink
export const POST_UPDATE_DRINK_REQUEST= "POST_UPDATE_DRINK_REQUEST";
export const POST_UPDATE_DRINK_SUCCESS = "POST_UPDATE_DRINK_SUCCESS";
export const POST_UPDATE_DRINK_ERROR = "POST_UPDATE_DRINK_ERROR";

// post delete drink
export const POST_DELETE_DRINK_REQUEST= "POST_DELETE_DRINK_REQUEST";
export const POST_DELETE_DRINK_SUCCESS = "POST_DELETE_DRINK_SUCCESS";
export const POST_DELETE_DRINK_ERROR = "POST_DELETE_DRINK_ERROR";

// post customize Number
export const POST_CUSTOMIZE_NUMBER_REQUEST= "POST_CUSTOMIZE_NUMBER_REQUEST";
export const POST_CUSTOMIZE_NUMBER_SUCCESS = "POST_CUSTOMIZE_NUMBER_SUCCESS";
export const POST_CUSTOMIZE_NUMBER_ERROR = "POST_CUSTOMIZE_NUMBER_ERROR";

// post customize Number
export const POST_CUSTOMIZE_QUEUE_REQUEST= "POST_CUSTOMIZE_QUEUE_REQUEST";
export const POST_CUSTOMIZE_QUEUE_SUCCESS = "POST_CUSTOMIZE_QUEUE_SUCCESS";
export const POST_CUSTOMIZE_QUEUE_ERROR = "POST_CUSTOMIZE_QUEUE_ERROR";