export const GET_POST_DETAIL_REQUEST = "GET_POST_DETAIL_REQUEST";
export const GET_POST_DETAIL_SUCCESS = "GET_POST_DETAIL_SUCCESS";
export const GET_POST_DETAIL_ERROR = "GET_POST_DETAIL_ERROR";

export const POST_THANK_REQUEST = "POST_THANK_REQUEST";
export const POST_THANK_SUCCESS = "POST_THANK_SUCCESS";
export const POST_THANK_ERROR = "POST_THANK_ERROR";

export const GET_ANNOUNCEMENT = "GET_ANNOUNCEMENT";
export const GET_ANNOUNCEMENT_SUCCESS = "GET_ANNOUNCEMENT_SUCCESS";
export const GET_ANNOUNCEMENT_ERROR = "GET_ANNOUNCEMENTT_ERROR";

export const GET_ALL_NEWSFEED = "GET_ALL_NEWSFEED";
export const GET_ALL_NEWSFEED_SUCCESS = "GET_ALL_NEWSFEED_SUCCESS";
export const GET_ALL_NEWSFEED_ERROR = "GET_ALL_NEWSFEED_ERROR";

export const GET_DEPARTMENT_REQUEST = "GET_DEPARTMENT";
export const GET_DEPARTMENT_SUCCESS = "DEPARTMENT_SUCCESS";
export const GET_DEPARTMENT_ERROR = "DEPARTMENT_ERROR";

export const POST_SEEN_REQUEST = "POST_SEEN_REQUEST";
export const POST_SEEN_SUCCESS = "POST_SEEN_SUCCESS";
export const POST_SEEN_ERROR = "POST_SEEN_ERROR";

export const GET_REACTION_REQUEST = "GET_REACTION_REQUEST";
export const GET_REACTION_SUCCESS = "GET_REACTION_SUCCESS";
export const GET_REACTION_ERROR = "GET_REACTION_ERROR";

export const POST_REACTION_REQUEST = "POST_REACTION_REQUEST";
export const POST_REACTION_SUCCESS = "POST_REACTION_SUCCESS";
export const POST_REACTION_ERROR = "POST_REACTION_ERROR";

export const DELETE_REACTION_REQUEST = "DELETE_REACTION_REQUEST";
export const DELETE_REACTION_SUCCESS = "DELETE_REACTION_SUCCESS";
export const DELETE_REACTION_ERROR = "DELETE_REACTION_ERROR";
