export const UPDATE_PROFILE_REQUEST = "UPDATE_PROFILE_REQUEST";
export const UPDATE_PROFILE_SUCCESS = "UPDATE_PROFILE_SUCCESS";
export const UPDATE_PROFILE_ERROR = "UPDATE_PROFILE_ERROR";

export const GET_ALL_FRIEND = "GET_ALL_FRIEND";
export const GET_ALL_FRIEND_SUCCESS = "GET_ALL_FRIEND_SUCCESS";
export const GET_ALL_FRIEND_ERROR = "GET_ALL_FRIEND_ERROR";

export const GET_INFO_REQUEST = "GET_INFO_REQUEST";
export const GET_USERS_SUCCESS = "GET_USERS_SUCCESS";
export const GET_USERS_ERROR = "GET_USERS_ERROR";

export const EDIT_PROFILE = "EDIT_PROFILE";
export const PROFILE_SUCCESS = "PROFILE_SUCCESS";
export const PROFILE_ERROR = "PROFILE_ERROR";

export const GET_PERSONAL_USER = "GET_PERSONAL_USER";
export const GET_PERSONAL_USER_SUCCESS = "GET_PERSONAL_USER_SUCCESS";
export const GET_PERSONAL_USER_ERROR = "GET_PERSONAL_USER_ERROR";
export const GET_PERSONAL_USER_ID = "GET_PERSONAL_USER_ID";
