//all category

export const GET_ALL_CATEGORY_REQUEST = "GET_ALL_CATEGORY_REQUEST";
export const GET_ALL_CATEGORY_SUCCESS = "GET_ALL_CATEGORY_SUCCESS";
export const GET_ALL_CATEGORY_ERROR = "GET_ALL_CATEGORY_ERROR";

//all menu

export const GET_ALL_MENU_REQUEST = "GET_ALL_MENU_REQUEST";
export const GET_ALL_MENU_SUCCESS = "GET_ALL_MENU_SUCCESS";
export const GET_ALL_MENU_ERROR = "GET_ALL_MENU_ERROR";

//all search

export const GET_ALL_SEARCH_REQUEST = "GET_ALL_SEARCH_REQUEST";
export const GET_ALL_SEARCH_SUCCESS = "GET_ALL_SEARCH_SUCCESS";
export const GET_ALL_SEARCH_ERROR = "GET_ALL_SEARCH_ERROR";

//call waiter

export const POST_CALL_WAITER_REQUEST = "POST_CALL_WAITER_REQUEST";
export const POST_CALL_WAITER_SUCCESS = "POST_CALL_WAITER_SUCCESS";
export const POST_CALL_WAITER_ERROR = "POST_CALL_WAITER_ERROR";

//call payment

export const POST_CALL_PAYMENT_REQUEST = "POST_CALL_PAYMENT_REQUEST";
export const POST_CALL_PAYMENT_SUCCESS = "POST_CALL_PAYMENT_SUCCESS";
export const POST_CALL_PAYMENT_ERROR = "POST_CALL_PAYMENT_ERROR";

//send Feedback

export const SEND_FEEDBACK_REQUEST = "SEND_FEEDBACK_REQUEST";
export const SEND_FEEDBACK_SUCCESS = "SEND_FEEDBACK_SUCCESS";
export const SEND_FEEDBACK_ERROR = "SEND_FEEDBACK_ERROR";

//get all food

export const GET_FOOD_IN_COMBO_REQUEST = "GET_FOOD_IN_COMBO_REQUEST";
export const GET_FOOD_IN_COMBO_SUCCESS = "GET_FOOD_IN_COMBO_SUCCESS";
export const GET_FOOD_IN_COMBO_ERROR = "GET_FOOD_IN_COMBO_ERROR";