//all category

export const GET_ALL_CATEGORY_REQUEST = "GET_ALL_CATEGORY_REQUEST";
export const GET_ALL_CATEGORY_SUCCESS = "GET_ALL_CATEGORY_SUCCESS";
export const GET_ALL_CATEGORY_ERROR = "GET_ALL_CATEGORY_ERROR";

//all menu

export const GET_ALL_MENU_REQUEST = "GET_ALL_MENU_REQUEST";
export const GET_ALL_MENU_SUCCESS = "GET_ALL_MENU_SUCCESS";
export const GET_ALL_MENU_ERROR = "GET_ALL_MENU_ERROR";

//add to cart menu

export const ADD_TO_CART_MENU_REQUEST = "ADD_TO_CART_MENU_REQUEST";
export const ADD_TO_CART_MENU_SUCCESS = "ADD_TO_CART_MENU_SUCCESS";
export const ADD_TO_CART_MENU_ERROR = "ADD_TO_CART_MENU_ERROR";

//all search

export const GET_ALL_SEARCH_REQUEST = "GET_ALL_SEARCH_REQUEST";
export const GET_ALL_SEARCH_SUCCESS = "GET_ALL_SEARCH_SUCCESS";
export const GET_ALL_SEARCH_ERROR = "GET_ALL_SEARCH_ERROR";

//call waiter

export const POST_CALL_WAITER_REQUEST = "POST_CALL_WAITER_REQUEST";
export const POST_CALL_WAITER_SUCCESS = "POST_CALL_WAITER_SUCCESS";
export const POST_CALL_WAITER_ERROR = "POST_CALL_WAITER_ERROR";

//call payment

export const POST_CALL_PAYMENT_REQUEST = "POST_CALL_PAYMENT_REQUEST";
export const POST_CALL_PAYMENT_SUCCESS = "POST_CALL_PAYMENT_SUCCESS";
export const POST_CALL_PAYMENT_ERROR = "POST_CALL_PAYMENT_ERROR";

//send Feedback

export const SEND_FEEDBACK_REQUEST = "SEND_FEEDBACK_REQUEST";
export const SEND_FEEDBACK_SUCCESS = "SEND_FEEDBACK_SUCCESS";
export const SEND_FEEDBACK_ERROR = "SEND_FEEDBACK_ERROR";

//get all food

export const GET_FOOD_IN_COMBO_REQUEST = "GET_FOOD_IN_COMBO_REQUEST";
export const GET_FOOD_IN_COMBO_SUCCESS = "GET_FOOD_IN_COMBO_SUCCESS";
export const GET_FOOD_IN_COMBO_ERROR = "GET_FOOD_IN_COMBO_ERROR";

//add to cart

export const ADD_TO_CART_REQUEST = "ADD_TO_CART_REQUEST";
export const ADD_TO_CART_SUCCESS = "ADD_TO_CART_SUCCESS";
export const ADD_TO_CART_ERROR = "ADD_TO_CART_ERROR";

//get cart

export const GET_CART_REQUEST = "GET_CART_REQUEST";
export const GET_CART_SUCCESS = "GET_CART_SUCCESS";
export const GET_CART_ERROR = "GET_CART_ERROR";

//delete from cart

export const DELETE_FROM_CART_REQUEST = "DELETE_FROM_CART_REQUEST";
export const DELETE_FROM_CART_SUCCESS = "DELETE_FROM_CART_SUCCESS";
export const DELETE_FROM_CART_ERROR = "DELETE_FROM_CART_ERROR";

//delete all from cart

export const DELETE_ALL_FROM_CART_REQUEST = "DELETE_ALL_FROM_CART_REQUEST";
export const DELETE_ALL_FROM_CART_SUCCESS = "DELETE_ALL_FROM_CART_SUCCESS";
export const DELETE_ALL_FROM_CART_ERROR = "DELETE_ALL_FROM_CART_ERROR";

//call payment

export const SEND_ORDER_REQUEST = "SEND_ORDER_REQUEST";
export const SEND_ORDER_SUCCESS = "SEND_ORDER_SUCCESS";
export const SEND_ORDER_ERROR = "SEND_ORDER_ERROR";

//view order

export const GET_VIEW_ORDER_REQUEST = "GET_VIEW_ORDER_REQUEST";
export const GET_VIEW_ORDER_SUCCESS = "GET_VIEW_ORDER_SUCCESS";
export const GET_VIEW_ORDER_ERROR = "GET_VIEW_ORDER_ERROR";

//check queue order

export const CHECK_QUEUE_ORDER_REQUEST = "CHECK_QUEUE_ORDER_REQUEST";
export const CHECK_QUEUE_ORDER_SUCCESS = "CHECK_QUEUE_ORDER_SUCCESS";
export const CHECK_QUEUE_ORDER_ERROR = "CHECK_QUEUE_ORDER_ERROR";