//all category

export const GET_ALL_CATEGORY_REQUEST = "GET_ALL_CATEGORY_REQUEST";
export const GET_ALL_CATEGORY_SUCCESS = "GET_ALL_CATEGORY_SUCCESS";
export const GET_ALL_CATEGORY_ERROR = "GET_ALL_CATEGORY_ERROR";

//all menu

export const GET_ALL_MENU_REQUEST = "GET_ALL_MENU_REQUEST";
export const GET_ALL_MENU_SUCCESS = "GET_ALL_MENU_SUCCESS";
export const GET_ALL_MENU_ERROR = "GET_ALL_MENU_ERROR";

//all search

export const GET_ALL_SEARCH_REQUEST = "GET_ALL_SEARCH_REQUEST";
export const GET_ALL_SEARCH_SUCCESS = "GET_ALL_SEARCH_SUCCESS";
export const GET_ALL_SEARCH_ERROR = "GET_ALL_SEARCH_ERROR";