export const CUSTOMER_LOGIN_USER = "CUSTOMER_LOGIN_USER";
export const CUSTOMER_LOGIN_SUCCESS = "CUSTOMER_LOGIN_SUCCESS";
export const AUTHORIZATION_USER_CUS = "AUTHORIZATION_USER_CUS";
export const CUSTOMER_LOGOUT_USER = "CUSTOMER_LOGOUT_USER";
export const CUSTOMER_LOGOUT_USER_SUCCESS = "CUSTOMER_LOGOUT_USER_SUCCESS";
export const API_ERROR_CUSTOMER = "LOGIN_API_ERROR";
export const SET_DATA = "SET_DATA";
export const TOKEN_STATUS_INVALID_CUSTOMER = "TOKEN_STATUS_INVALID_CUSTOMER";
